// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSrIJOLArWP-Ve9Rin4ZTE6ggLe6I4SA',
    appId: '1:345811778070:web:bc2b0adf0303114cde1337',
    messagingSenderId: '345811778070',
    projectId: 'resume-app-fe7b8',
    authDomain: 'resume-app-fe7b8.firebaseapp.com',
    storageBucket: 'resume-app-fe7b8.appspot.com',
    measurementId: 'G-Q9J6RZH7BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVIr32WHfdqUFwqWMNC8ta9l2_DN0Najg',
    appId: '1:345811778070:android:eaf4e5ed4cd89646de1337',
    messagingSenderId: '345811778070',
    projectId: 'resume-app-fe7b8',
    storageBucket: 'resume-app-fe7b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAHGnOlZzmp9csgMEX9VzZT-P8FTrnogo',
    appId: '1:345811778070:ios:0ebd55af8f61d7e8de1337',
    messagingSenderId: '345811778070',
    projectId: 'resume-app-fe7b8',
    storageBucket: 'resume-app-fe7b8.appspot.com',
    iosBundleId: 'com.example.resumeBuilderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAHGnOlZzmp9csgMEX9VzZT-P8FTrnogo',
    appId: '1:345811778070:ios:0ebd55af8f61d7e8de1337',
    messagingSenderId: '345811778070',
    projectId: 'resume-app-fe7b8',
    storageBucket: 'resume-app-fe7b8.appspot.com',
    iosBundleId: 'com.example.resumeBuilderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmSrIJOLArWP-Ve9Rin4ZTE6ggLe6I4SA',
    appId: '1:345811778070:web:cb9151f9073846adde1337',
    messagingSenderId: '345811778070',
    projectId: 'resume-app-fe7b8',
    authDomain: 'resume-app-fe7b8.firebaseapp.com',
    storageBucket: 'resume-app-fe7b8.appspot.com',
    measurementId: 'G-R05G2JMG7J',
  );
}
